# Generated by Django 4.2.27 on 2026-04-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0073_alter_updatecheckstatus_last_checked_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('path',), name='job_path_unique'),
        ),
    ]
